apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    environment: DEV
  name: balance-deployment
  namespace: default
spec:
  replicas: 5
  minReadySeconds: 20
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      pod: balance-pod
  template:
    metadata:
      labels:
        app: balance
        pod: balance-pod
    spec:
      containers:
        - name: balance-container
          image: jsierra93/api-balance:1.1
          imagePullPolicy: Never  # IfNotPresent / Always / Never
          ports:
            - name: balance
              containerPort: 8081
              protocol: TCP